# ./.tumxinator.yml

name: {{project-name}}
root: ./

windows:
  - main:
      layout: main-vertical
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - cargo watch -i lib -x "run --features reload"
        - cargo watch -w lib -x "build -p lib"
