[workspace]
resolver = "2"
members = ["lib"]

[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "./lib" }
hot-lib-reloader = { version = "*", optional = true }

[features]
default = ["reload"]
reload = ["dep:hot-lib-reloader"]
